---
- name: Update Debian-based systems
  hosts: all
  become: yes  # Run tasks as root

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
